### ISSUE TITLE
大佬，如何更新ip的数据。

### ISSUE THREAD

**Issue by molihuan** [aknife2019/ip#1]
我想自己更新一下ip数据,请问我该如何做,可不可以写在Readme中,非常感谢

**Comment by aknife2019** [comment]
使用php或者其他语言先处IP数据库为csv格式
纯真数据类型如下 
`id,start_ip,end_ip,continent_name,continent_name_en,continent_code,country_name,country_name_en,country_code,region_name,region_name_en,city_name,city_name_en` 

geo ip数据类型如下 
`id,ip,continent_name,continent_name_en,continent_code,country_name,country_name_en,country_code,region_name,region_name_en,city_name,city_name_en` 

然后使用 perl生成mmdb数据库( 官方建议使用golang  https://github.com/maxmind/mmdbwriter)



[createData.pl.zip](https://github.com/user-attachments/files/15759304/createData.pl.zip)

**Comment by molihuan** [comment]
> 使用php或者其他语言先处IP数据库为csv格式
> 纯真数据类型如下 
> `id,start_ip,end_ip,continent_name,continent_name_en,continent_code,country_name,country_name_en,country_code,region_name,region_name_en,city_name,city_name_en` 
> 
> geo ip数据类型如下 
> `id,ip,continent_name,continent_name_en,continent_code,country_name,country_name_en,country_code,region_name,region_name_en,city_name,city_name_en` 
> 
> 然后使用 perl生成mmdb数据库( 官方建议使用golang  https://github.com/maxmind/mmdbwriter)
> 
> 
> 
> [createData.pl.zip](https://github.com/user-attachments/files/15759304/createData.pl.zip)

感谢
